code: 0
swordName: Sword of Flames
swordSpecialSword: 1
swordSpecialPower: 3
candiesNbrOwned: 1061
candiesNbrThrown: 1000
candiesNbrEaten: 9825
candiesNbrTotal: 8418
candiesCandiesPerSecond: 3
candiesConverterActivated: 0
cauldronBookPage: 0
cauldronCandies: 0
cauldronLollipops: 0
chocolateBarsNbrOwned: 0
farmLollipopsPlanted: 25000
farmCurrentFlagIndex: 0
farmPlantingButtonsStep: 4
forgeStep: 2
shopLollipopsButtonsShown: 1
shopShown: 1
shopTicklingStep: 0
shopClickingOnLollipopStep: 0
hutStep: 2
hutSpeech: Congratulations ! You will now gain more candies each second !
inventoryMagicianHatLetter:      v
lollipopsNbrOwned: 42900
lollipopsNbrInStock: 81
lollipopsNbrBought: 76
mainNbrOfSecondsSinceLastMinInterval: 46
mainNbrOfSecondsSinceLastHourInterval: 2386
mainNbrOfSecondsSinceLastDayInterval: 2386
mountGoblinBasicChestProbability: 150
peacefulForestBasicChestProbability: 100
peacefulForestPoniesEncountered: 0
objectsHaveObjectKey: 1
objectsHaveObjectHutMap: 1
objectsHaveObjectWellMap: 1
objectsHaveObjectSwampMap: 1
objectsHaveObjectBoots: 1
objectsHaveObjectMagicianHat: 1
objectsHaveObjectPinkRing: 1
objectsHaveObjectForgeMap: 1
objectsHaveObjectCandiesConverter: 0
objectsHaveObjectPlateArmour: 0
objectsHaveObjectCauldron: 0
objectsHaveObjectMagicalHorn: 0
objectsHaveObjectHornOfPlenty: 0
objectsHaveObjectOldAmulet: 0
potionsShownHealth: 1
potionsShownEscape: 1
potionsShownBerserk: 1
potionsShownFireScroll: 1
potionsShownAcidRainScroll: 0
potionsShownTeleportScroll: 1
potionsShownEarthquakeScroll: 0
potionsShownImpInvocationScroll: 0
potionsShownMajorHealth: 0
potionsShownInvulnerability: 0
potionsShownTurtle: 0
potionsShownJelly: 0
potionsShownSeed: 0
potionsShownCloning: 0
potionsShownSuperman: 0
potionsShownGmooh: 0
potionsNbrOwnedHealth: 0
potionsNbrOwnedEscape: 0
potionsNbrOwnedBerserk: 5
potionsNbrOwnedFireScroll: 1
potionsNbrOwnedAcidRainScroll: 0
potionsNbrOwnedTeleportScroll: 1
potionsNbrOwnedEarthquakeScroll: 0
potionsNbrOwnedImpInvocationScroll: 0
potionsNbrOwnedMajorHealth: 0
potionsNbrOwnedInvulnerability: 0
potionsNbrOwnedTurtle: 0
potionsNbrOwnedJelly: 0
potionsNbrOwnedSeed: 0
potionsNbrOwnedCloning: 0
potionsNbrOwnedSuperman: 0
potionsNbrOwnedGmooh: 0
questMaxLandOrder: 4
questTiredTime: 139
spellsFasterCandiesFibo1: 3
spellsFasterCandiesFibo2: 5
swampStep: 17
tabsAnimation: none
wishingWellSpeech: Multiplicatus, multiplicata, multiplicatum ! Your lollipops are now multiplied !
wishingWellStep: 2
yourselfCanSurpass: 0
developperComputerWon: 0